@echo off
setlocal enabledelayedexpansion
cd /d "%~dp0"

echo.
echo ============================================================
echo   ICDSS - Intelligent Clinical Decision Support System
echo ============================================================
echo.

where docker >nul 2>&1
if %errorlevel% neq 0 (
    echo   ERROR: Docker was not found on PATH.
    echo   Install and start Docker Desktop, then run this file again.
    echo.
    pause
    exit /b 1
)

docker info >nul 2>&1
if %errorlevel% neq 0 (
    echo   ERROR: Docker Desktop is not running.
    echo   Start Docker Desktop, wait until it is ready, then run this file again.
    echo.
    pause
    exit /b 1
)

if not exist raw_data mkdir raw_data
if not exist processed_data mkdir processed_data
if not exist data mkdir data

if not exist .env (
    echo   Creating default .env file...
    (
    echo NEO4J_AUTH=neo4j/icdss_secure_2026
    echo DB_PASSWORD=icdss_secure_2026
    echo SALT_KEY=a7f3c9e1b2d4f6a8c0e2d4b6a8f0c2e4
    echo OLLAMA_MODEL=llama3:8b
    echo NEO4J_URI=bolt://neo4j:7687
    echo NEO4J_USER=neo4j
    echo PROCESSED_DATA_DIR=/app/processed_data
    echo TRACE_FILE=/app/processed_data/trace.json
    ) > .env
    echo   Written: .env
    echo.
)

if "%~1"=="--reconfigure" (
    if exist docker-compose.override.yml del docker-compose.override.yml
    echo   Cleared previous GPU configuration.
    echo.
)

if exist docker-compose.override.yml (
    echo   Existing Docker override found. Use 'start.bat --reconfigure' to regenerate it.
    echo.
    goto :launch
)

echo   Detecting NVIDIA GPU...
echo.

nvidia-smi --query-gpu=name,memory.total --format=csv,noheader,nounits >nul 2>&1
if %errorlevel% neq 0 (
    echo   No NVIDIA GPU detected. Ollama will run in CPU-only mode.
    echo   This is fully functional, just slower on LLM calls.
    echo.
    goto :write_cpu
)

echo   GPU detected:
for /f "tokens=1,2 delims=," %%a in ('nvidia-smi --query-gpu^=name^,memory.total --format^=csv^,noheader^,nounits') do (
    set "GPU_NAME=%%a"
    set "GPU_VRAM=%%b"
    echo     %%a ^(%%b MB VRAM^)
)
echo.

echo   Enabling GPU acceleration for Ollama...
(
echo # Auto-generated by start.bat - NVIDIA GPU acceleration for Ollama
echo services:
echo   ollama:
echo     deploy:
echo       resources:
echo         reservations:
echo           devices:
echo             - driver: nvidia
echo               count: all
echo               capabilities: [gpu]
) > docker-compose.override.yml
echo   Written: docker-compose.override.yml ^(GPU mode^)

set /a VRAM_INT=!GPU_VRAM!
if !VRAM_INT! lss 6000 (
    echo.
    echo   GPU VRAM is below 6 GB. Switching to lighter model llama3.2:1b for one-click reliability.
    powershell -NoProfile -Command "(Get-Content .env) -replace 'OLLAMA_MODEL=.*', 'OLLAMA_MODEL=llama3.2:1b' | Set-Content .env"
    echo   Updated .env: OLLAMA_MODEL=llama3.2:1b
)

goto :launch

:write_cpu
(
echo # Auto-generated by start.bat - CPU-only mode
echo # Re-run 'start.bat --reconfigure' to enable GPU.
echo services: {}
) > docker-compose.override.yml
echo   Written: docker-compose.override.yml ^(CPU mode^)

:launch
echo.
echo   Starting ICDSS services...
echo   First launch downloads the selected Ollama model. This may take several minutes.
echo.

docker compose up -d --build
if %errorlevel% neq 0 (
    echo.
    echo   ERROR: Docker Compose failed to start ICDSS.
    echo   Run 'docker compose logs app' for details.
    echo.
    pause
    exit /b 1
)

echo.
echo   Waiting for Streamlit app health check...
powershell -NoProfile -ExecutionPolicy Bypass -Command "$deadline=(Get-Date).AddMinutes(5); do { try { $r=Invoke-WebRequest -UseBasicParsing -Uri 'http://127.0.0.1:8501/_stcore/health' -TimeoutSec 3; if ($r.StatusCode -eq 200) { exit 0 } } catch {}; Start-Sleep -Seconds 3 } while ((Get-Date) -lt $deadline); exit 1"
if %errorlevel% neq 0 (
    echo   App is still starting. Opening the browser anyway.
) else (
    echo   App is healthy.
)

start "" "http://127.0.0.1:8501"

echo.
echo ============================================================
echo   ICDSS is ready. Browser opened at http://127.0.0.1:8501
echo   Use the sidebar to run the data pipeline and ingestion.
echo ============================================================
echo.

endlocal
